name: go
channels:
  - defaults
dependencies:
  - _r-mutex=1.0.0
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - curl=7.62.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib=2.56.2
  - graphite2=1.3.12
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=1.8.8
  - icu=58.2
  - libcurl=7.62.0
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.35
  - libssh2=1.8.0
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - make=4.2.1
  - mro-base=3.5.1
  - mro-base_impl=3.5.1
  - mro-basics=3.5.1
  - openssl=1.1.1
  - pango=1.42.4
  - pcre=8.42
  - pixman=0.34.0
  - r=3.5.1
  - r-boot=1.3_20
  - r-checkpoint=0.4.4
  - r-class=7.3_14
  - r-cluster=2.0.7_1
  - r-codetools=0.2_15
  - r-curl=3.2
  - r-deployrrserve=9.0.0
  - r-doparallel=1.0.13
  - r-foreach=1.5.0
  - r-foreign=0.8_70
  - r-iterators=1.0.10
  - r-jsonlite=1.5
  - r-kernsmooth=2.23_15
  - r-lattice=0.20_35
  - r-mass=7.3_49
  - r-matrix=1.2_14
  - r-mgcv=1.8_23
  - r-microsoftr=3.5.0.108
  - r-nlme=3.1_137
  - r-nnet=7.3_12
  - r-png=0.1_7
  - r-r6=2.2.2
  - r-recommended=3.5.1
  - r-revoioq=10.0.0
  - r-revomods=11.0.0
  - r-revoutils=11.0.0
  - r-revoutilsmath=11.0.0
  - r-rpart=4.1_13
  - r-runit=0.4.26
  - r-spatial=7.3_11
  - r-survival=2.41_3
  - xz=5.2.4
  - zlib=1.2.11
